# Generated by Django 5.0.2 on 2024-10-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_depressionanxiety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoruser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='education',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='state',
        ),
    ]
